CREATE TABLE IF NOT EXISTS project_phones (
    id INT AUTO_INCREMENT PRIMARY KEY,
    api_id VARCHAR (255) DEFAULT NULL,
    phone_brand VARCHAR (100) NOT NULL,
    phone_model VARCHAR (100) NOT NULL,
    screen_size VARCHAR (50) DEFAULT NULL,
    camera_megapixels VARCHAR (50) DEFAULT NULL, 
    is_api TINYINT(1) DEFAULT 0,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY (api_id)
);