CREATE TABLE IF NOT EXISTS user_phones (
    id INT NOT NULL AUTO_INCREMENT,
    user_id INT NOT NULL,
    phone_id INT NOT NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modified TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE (user_id, phone_id),
    FOREIGN KEY (user_id) REFERENCES Users (id) ON DELETE CASCADE,
    FOREIGN KEY (phone_id) REFERENCES project_phones (id) ON DELETE CASCADE
);